name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.prepare.outputs.dir }}
    steps:
      - name: Prepare
        run: echo "::set-output name=dir::/path/to/build/dir"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: echo "Build code is located in ${{ needs.build.outputs.build-dir }}"
